### ISSUE TITLE
21-03-04 06:30:29 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of SONOS AudioClip TTS

### ISSUE THREAD

**Issue by jvalst** [kevinvincent/hassio-addons#16]
Since latest update 2021-03 there is an log error in the system. 

21-03-04 06:30:29 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of SONOS AudioClip TTS

**Comment by jvalst** [comment]
Is it possible to have a look at this warning? Not sure what will happen if they completely remove it. Thanks in advance :)

**Comment by patchrick84** [comment]
Is this why I've been having mixed success with this add-on?  I keep getting token errors and such.  Once I re-authenticate it with the Sonos Developer site, it works fine for a day or two.  But then starts throwing errors again.

Here's the most recent log entry:

(node:214) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
Access Token Error Cannot create access token without a token to parse
(node:214) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:518:11)
    at /app/server/index.js:378:16
(node:214) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
15:51:15 ✨ request completed GET 200 /api/playClipAll?&streamUrl=mailishere.mp3&volume=25&exclude=Backyard&prio=low 3ms

**Comment by jvalst** [comment]
Hmm, I'm not sure about that error. In my place the plugin is still working fine, but it's been flagged that there is use of a deprecated config. So that's why I posted it here to maybe see if @kevinvincent or someone can fix it before the whole plugin isn't working anymore. 

Not sure what's wrong in your place. I've just followed the documentation and it's been running for like 1 month now here without issues.

**Comment by patchrick84** [comment]
Okay.  After reading your posts more closely I see that our issues are unrelated.  I do, however, see the deprecated message in my logs as well.  So hopefully one of the gurus here takes a look at it and gets that fixed up ASAP.

**Comment by jvalst** [comment]
It's in the config file where there is startup; before. According the documentation it should be something as "application". 

https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
