### ISSUE TITLE
Token Errors, I think...

### ISSUE THREAD

**Issue by patchrick84** [kevinvincent/hassio-addons#17]
My experience with the add on has been mixed.  At first it worked fine for the few months I've had it installed.  At some point though, this started happening.  Once I re-authenticate it with the Sonos Developer site, it works fine for a day or two.  But then starts throwing errors again.  I'm not a developer in any shape of the word, so all of this is gibberish to me.  Hoping one of the gurus here can help me out!

Here's the most recent log entry:

(node:214) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
Access Token Error Cannot create access token without a token to parse
(node:214) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:518:11)
    at /app/server/index.js:378:16
(node:214) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
15:51:15 ✨ request completed GET 200 /api/playClipAll?&streamUrl=mailishere.mp3&volume=25&exclude=Backyard&prio=low 3ms

_Originally posted by @patchrick84 in https://github.com/kevinvincent/hassio-addons/issues/16#issuecomment-792053080_

**Comment by jnbht** [comment]
I have a similar experience. It works fine for a while, then stops working and i need to re-auth the system.
Don't know why it looses the token.
